version: '2.0'
services:
  filepod:
    image: 'filepod:1.3.0'
    container_name: 'filepod'
    environment:
      LOG_HOME: '/logs'
      LogbackConfigFile: 'logback-file.xml'
      FilpodConfigPath: '/config'
    ports:
      - '8080:8080'
    volumes:
      - './config:/config'
      - './logs:/logs'
