cors:
  allowed:
    origins: "*"
    methods: "GET,POST,OPTIONS,HEAD"
    headers: "Content-Type,Content-Length,Host,User-Agent,Cache-Control,Accept,Accept-Encoding,Connection"
  exposed:
    headers: "CONCRETE-TOKEN-ID"
  support:
    credentials: "false"
  preflight:
    maxage: "1800"
  request:
    decorate: "true"