testTotp:
  scope: "*"
  controller: "totp"
  totpSecret: "MjAyMDA0MTUxNTMxMzAK"

testConcrete:
  scope: "*"
  controller: "concrete"
  clientUrl: "http://127.0.0.1:8090/Client"

testConcreteV04x:
  scope: "*"
  controller: "concrete_v0.4.x"
  clientUrl: "http://127.0.0.1:8090/Client"

testFeedback:
  scope: "*"
  controller: "session"
  clientUrl: "http://127.0.0.1:8090/Client"
